# Generated by Django 4.2.1 on 2023-05-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT',
        ),
    ]
