# Generated by Django 4.2.1 on 2023-05-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='dob',
        ),
    ]
